site_name: SafeChord Docs

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.indexes
    - content.code.copy
    - content.action.edit
    - navigation.footer
  custom_dir: overrides
  palette:
  - scheme: default
    primary: indigo
    toggle:
      icon: material/weather-night
      name: 切換至深色模式
  - scheme: slate
    primary: indigo
    toggle:
      icon: material/weather-sunny
      name: 切換至淺色模式

nav:
  - Home: safechord.md
  - SafeZone:
      - Overview:
          - Concept: safechord.safezone.md
          - ChangeLog: safechord.safezone.changelog.md
      - CI/CD: safechord.safezone.ci-cd.md
      - Deployment:
          - Overview: safechord.safezone.deployment.md
          - SafeZone-Infra: safechord.safezone.deployment.safezone-infra.md
          - SafeZone-Core: safechord.safezone.deployment.safezone-core.md
          - SafeZone-Init: safechord.safezone.deployment.safezone-init.md
          - SafeZone-UI: safechord.safezone.deployment.safezone-ui.md
      - Service:
          - Overview: safechord.safezone.service.md
          - DataSimulator: safechord.safezone.service.pandemicsimulator.md
          - DataIgestor: safechord.safezone.service.dataingestor.md
          - AnalyticsAPI: safechord.safezone.service.analyticsapi.md
          - Dashboard: safechord.safezone.service.dashboard.md
      - Toolkit:
          - SafeZone-CLI: safechord.safezone.toolkit.cli.md
          - Time-Server: safechord.safezone.toolkit.timeserver.md
  - Chorde:
      - K3han:
          - Overview: safechord.chorde.k3han.md
          - Cluster: safechord.chorde.k3han.cluster.md
          - Build: safechord.chorde.k3han.build.md
          - Monitoring: safechord.chorde.k3han.monitoring.md
          - Scheduling: safechord.chorde.k3han.scheduling.md
  - Document Map: safechord.knowledgetree.md
  - Reference: safechord.reference.md
