site_name: SafeChord Docs

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.indexes
    - content.code.copy
    - content.action.edit
    - navigation.footer
  custom_dir: overrides
  palette:
  - scheme: default
    primary: indigo
    toggle:
      icon: material/weather-night
      name: åˆ‡æ›è‡³æ·±è‰²æ¨¡å¼
  - scheme: slate
    primary: indigo
    toggle:
      icon: material/weather-sunny
      name: åˆ‡æ›è‡³æ·ºè‰²æ¨¡å¼

nav:
  - Home: safechord.md
  - ğŸ—ºï¸ Knowledge Tree: safechord.knowledgetree.md
  - ğŸŸ¦ SafeZone:
      - Overview: safechord.safezone.md
      - Services:
          - Architecture: safechord.safezone.service.md
          - Pandemic Simulator: safechord.safezone.service.pandemicsimulator.md
          - Data Ingestor: safechord.safezone.service.dataingestor.md
          - Worker (Golang): safechord.safezone.service.worker.md
          - Analytics API: safechord.safezone.service.analyticsapi.md
          - Dashboard: safechord.safezone.service.dashboard.md
      - Toolkit:
          - CLI (szcli): safechord.safezone.toolkit.cli.md
          - Command Ref: safechord.safezone.toolkit.cli.reference.md
          - Time Server: safechord.safezone.toolkit.timeserver.md
      - Workflow: safechord.safezone.workflow.md
      - ChangeLog: safechord.safezone.changelog.md
  - ğŸŸ¨ Deployment:
      - Overview: safechord.safezone.deployment.md
      - Helm Architecture: safechord.safezone.deployment.charts.md
      - Workflow: safechord.safezone.deployment.workflow.md
  - ğŸŸ¥ K3han Cluster:
      - Overview: safechord.chorde.k3han.md
      - Topology: safechord.chorde.k3han.cluster.md
      - Ingress: safechord.chorde.k3han.ingress.md
      - Scheduling: safechord.chorde.k3han.scheduling.md
      - Monitoring: safechord.chorde.k3han.monitoring.md
      - ChangeLog: safechord.chorde.k3han.changelog.md
  - ğŸŒ Environment: safechord.environment.md
  - ğŸ›¡ï¸ Security: safechord.security.md
  - â¬œ Methodology (KDD):
      - Introduction: safechord.kdd.introduction.md
      - Practice: safechord.kdd.practice.md
      - Workflow: safechord.kdd.workflow.md
